engines:
  pep8:
    enabled: true
    checks:
      E501: # Line length checks
        enabled: false
      E225:
        enabled: false
      W291:
        enabled: false
      E231:
        enabled: false
      E203:
        enabled: false
      E251:
        enabled: false
      W293:
        enabled: false
      E202:
        enabled: false
